#ifndef TPEARQUI_SNAKEMAIN_H
#define TPEARQUI_SNAKEMAIN_H

#define BGCOLOR_1 0x0022FF22
#define BGCOLOR_2 0x00AAFFAA
#define APPLECOLOR 0x00FF0000
typedef enum{SINGLE, DUOS} SNAKE_MODE;
int snake(SNAKE_MODE mode);

#endif //TPEARQUI_SNAKEMAIN_H
